version: '3.8'
services:
  netbox: &netbox
    container_name: netbox
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./data/media:/opt/netbox/netbox/media
      - ./scripts:/opt/netbox/netbox/scripts
      - ./plugins:/opt/netbox/plugins
    depends_on:
      - db
      - redis
      - redis-cache
      - netbox-worker
      - smtp
    environment:
      - DB_USER=netbox
      - DB_PASSWORD=develop
      - DB_HOST=netbox-db
      - SECRET_KEY=develop
      - REDIS_HOST=netbox-redis
      - REDIS_PASSWORD=develop
      - REDIS_CACHE_HOST=netbox-redis-cache
      - REDIS_CACHE_PASSWORD=develop
      - REDIS_CACHE_DATABASE=0
      - EMAIL_SERVER=smtp
      - EMAIL_USERNAME=netbox@init7.local
      - EMAIL_PASSWORD=1234
      - LOGIN_REQUIRED=true
      - MEDIA_ROOT=/opt/netbox/netbox/media
      - RELEASE_CHECK_URL=https://api.github.com/repos/netbox-community/netbox/releases
      - NAPALM_USERNAME=${NAPALM_USERNAME:-}
      - NAPALM_PASSWORD=${NAPALM_PASSWORD:-}
    ports:
      - "127.0.0.1:$NETBOX_HTTP_PORT:8080"
  netbox-worker:
    <<: *netbox
    container_name: netbox-worker
    depends_on:
      - db
      - redis
      - redis-cache
    entrypoint:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
    command:
      - rqworker
    expose: []
    ports: []
    labels: []
  db:
    container_name: netbox-db
    image: postgres:13.3-alpine@sha256:cd1b837c86e9c2df778b3b4ece70dcd5a74f3ea68f82d00714aec91f34ba328d
    environment:
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD
      - POSTGRES_DB=netbox
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    container_name: netbox-redis
    image: redis:6.2.5-alpine@sha256:ca9a5a3d4bb958793bb4c24034a3b99e5e13fb6a15b1a3ae70f9e21652a76aff
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=develop
  redis-cache:
    container_name: netbox-redis-cache
    image: redis:6.2.5-alpine@sha256:ca9a5a3d4bb958793bb4c24034a3b99e5e13fb6a15b1a3ae70f9e21652a76aff
    command:
      - sh
      - -c # this is to evaluate the $REDIS_CACHE_PASSWORD from the env
      - redis-server --requirepass $$REDIS_CACHE_PASSWORD ## $$ because of docker-compose
    environment:
      - REDIS_CACHE_PASSWORD=develop

  smtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - "127.0.0.1:$MAILHOG_HTTP_PORT:8025"
    networks:
      - default
    healthcheck:
      test: echo | telnet 127.0.0.1 25

networks:
  default: