# Generated by Django 4.0.3 on 2022-04-16 12:29

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_config_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtemplate',
            name='template_content',
            field=models.TextField(default='Hello World <>'),
        ),
        migrations.CreateModel(
            name='GraphQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('query_content', models.TextField()),
                ('context_key', models.CharField(max_length=50)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
