# Generated by Django 4.0.3 on 2022-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_manager', '0002_alter_configtemplate_template_content_graphqlquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplate',
            name='graphql_queries',
            field=models.ManyToManyField(to='netbox_config_manager.graphqlquery'),
        ),
    ]
