# Generated by Django 4.0.3 on 2022-04-26 07:30

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('netbox_config_manager', '0003_configtemplate_graphql_queries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphqlquery',
            options={'verbose_name': 'GraphQL Query', 'verbose_name_plural': 'GraphQL Queries'},
        ),
        migrations.CreateModel(
            name='TransportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('secret_reference', models.CharField(max_length=255)),
                ('authorization_manage_groups', models.ManyToManyField(related_name='transport_config_manage', to='auth.group')),
                ('authorization_manage_users', models.ManyToManyField(related_name='transport_config_manage', to=settings.AUTH_USER_MODEL)),
                ('authorization_usage_groups', models.ManyToManyField(related_name='transport_config_usage', to='auth.group')),
                ('authorization_usage_users', models.ManyToManyField(related_name='transport_config_usage', to=settings.AUTH_USER_MODEL)),
                ('config_contexts', models.ManyToManyField(to='extras.configcontext')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
